FROM golang:1.6

RUN go get github.com/eventials/frodo
RUN go get github.com/gorilla/mux
RUN go get github.com/streadway/amqp

EXPOSE 3000

WORKDIR $GOPATH/src/github.com/eventials/frodo

CMD go run server.go
